services:
  - type: web
    name: vault
    env: docker
    dockerfilePath: ./vault-server/Dockerfile
    plan: standard
    envVars:
      - key: VAULT_HOST
        value: 0.0.0.0
      - key: VAULT_PORT
        value: 3000
      - key: VAULT_METRICS_PORT
        value: 9090
      - key: VAULT_LOG_LEVEL
        value: info
      - key: VAULT_DATABASE_URL
        sync: false
      - key: VAULT_REDIS_URL
        sync: false
      - key: VAULT_JWT_SECRET
        sync: false
