apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault.fullname" . }}-secrets
  labels:
    app: {{ include "vault.name" . }}

type: Opaque
stringData:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
