{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vault.fullname" . }}-migrate
  labels:
    app: {{ include "vault.name" . }}

spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ include "vault.name" . }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["dbmate", "-d", "/app/migrations", "up"]
          envFrom:
            - configMapRef:
                name: {{ include "vault.fullname" . }}-config
            - secretRef:
                name: {{ include "vault.fullname" . }}-secrets
{{- end }}
