apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    app: {{ include "vault.name" . }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "vault.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
